# .github/workflows/python-app.yml
name: Python application

on:
  push:
    branches:
      - main  # Run tests on push to main branch
  pull_request:
    branches:
      - main  # Run tests on pull request to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-fail-under=90
